<?xml version="1.0"?>

<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Body dimensions: m -->
<xacro:property name="body_link_x_dim" value="1"/>    
<xacro:property name="body_link_y_dim" value="0.6"/>
<xacro:property name="body_link_z_dim" value="0.3"/>

<!-- Wheel dimensions: m -->
<xacro:property name="wheel_link_radius" value="0.15"/>
<xacro:property name="wheel_link_length" value="0.1"/>
<xacro:property name="wheel_link_z_location" value="-0.1"/>

<!-- Material density: kg/m^3 -->
<xacro:property name="body_density" value="2710.0"/>
<xacro:property name="wheel_density" value="2710.0"/>

<!-- Pi constant -->
<xacro:property name="pi" value="3.14159265359"/>

<!-- Robot body and wheel mass: density * volume -->
<xacro:property name="body_mass" value="${body_density * body_link_x_dim * body_link_y_dim * body_link_z_dim}" />
<xacro:property name="wheel_mass" value="${wheel_density * pi * (wheel_link_radius*wheel_link_radius) * wheel_link_length}" />

<!-- Moments of intertia of the wheel -->
<xacro:property name="Iz_wheel" value="${wheel_mass * (wheel_link_radius*wheel_link_radius) / 2}" />
<xacro:property name="I_wheel" value="${wheel_mass * (3 * (wheel_link_radius*wheel_link_radius) + wheel_link_length*wheel_link_length) / 12}" />

<!-- Macro defines complete inertial section of the wheel -->
<xacro:macro name="inertia_wheel">
    <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0.0" izz="${Iz_wheel}"/>
    </inertial>
</xacro:macro>

<xacro:include filename="$(find mobile_robot)/model/robot.gazebo"/>

<!-- DEFINE LINKS AND JOINTS HERE -->

<link name="dummy">
</link>
<joint name="dummy_joint" type="fixed">
    <parent link="dummy"/>
    <child link="body_link" />
</joint>

<!-- START: Body link of the robot -->
<link name="body_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia
        ixx="${(1/12) * body_mass * (body_link_y_dim*body_link_y_dim + body_link_z_dim*body_link_z_dim)}" ixy="0.0" ixz="0.0"
        iyy="${(1/12) * body_mass * (body_link_x_dim*body_link_x_dim + body_link_z_dim*body_link_z_dim)}" iyz="0.0"
        izz="${(1/12) * body_mass * (body_link_x_dim*body_link_x_dim + body_link_y_dim*body_link_y_dim)}" />
    </inertial>   
</link>

<!-- START: Back right wheel of the robot -->
<joint name="wheel1_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel1_link"/>
    <origin xyz="${-body_link_x_dim/2 + 1.2*wheel_link_radius} ${-body_link_y_dim/2 - wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>


<link name="wheel1_link">
    <visual>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
    </collision>
    <xacro:inertia_wheel />
</link>


<!-- START: Back left wheel of the robot and the joint -->
<joint name="wheel2_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel2_link"/>
    <origin xyz="${-body_link_x_dim/2 + 1.2*wheel_link_radius} ${body_link_y_dim/2 + wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel2_link">
    <visual>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
    </collision>
    <xacro:inertia_wheel />
</link>


<!-- START: Front right wheel of the robot and the joint -->
<joint name="wheel3_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel3_link"/>
    <origin xyz="${body_link_x_dim/2 - 1.2*wheel_link_radius} ${-body_link_y_dim/2 - wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel3_link">
    <visual>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
    </collision>
    <xacro:inertia_wheel />
</link>


<!-- START: Front left wheel of the robot and the joint -->
<joint name="wheel4_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel4_link"/>
    <origin xyz="${body_link_x_dim/2 - 1.2*wheel_link_radius} ${body_link_y_dim/2 + wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel4_link">
    <visual>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
    </collision>
    <xacro:inertia_wheel />
</link>


</robot>